### ISSUE TITLE
Only 1 band in image?

### ISSUE THREAD

**Issue by mankoff** [p-v-o-s/infrapix#4]
When I run the example command on the example image, I get the following error:

This is OS X with Enthought Python installed (2.7) and it appears to be a PIL error. I'm using PIL 1.1.7-12.

```
infrapix_single -i river.jpg --show_histogram -o ndvi_river.jpg
Rendering infrablue input image 'river.jpg' to NDVI output image 'ndvi_river.jpg'
river.jpg ndvi_river.jpg
Converting to NDVI...
Traceback (most recent call last):
  File "/Users/mankoff/Library/Enthought/Canopy_64bit/User/bin/infrapix_single", line 9, in <module>
    load_entry_point('infrapix==dev', 'console_scripts', 'infrapix_single')()
  File "/Users/mankoff/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/infrapix-dev-py2.7.egg/infrapix/commands/single.py", line 139, in main
    app.render()
  File "/Users/mankoff/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/infrapix-dev-py2.7.egg/infrapix/commands/single.py", line 43, in render
    self.render_single(**kwargs)
  File "/Users/mankoff/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/infrapix-dev-py2.7.egg/infrapix/commands/single.py", line 53, in render_single
    ndvi(self.input_file,self.output_file,**self.ndvi_kwargs)
  File "/Users/mankoff/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/infrapix-dev-py2.7.egg/infrapix/process_infrablue.py", line 70, in ndvi
    imgR, imgB, imgG = img.split() #get channels
  File "/Users/mankoff/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/PIL/Image.py", line 1497, in split
    if self.im.bands == 1:
AttributeError: 'NoneType' object has no attribute 'bands'
```

**Comment by agmcmanus** [comment]
I get the same error on Raspberry Pi Wheezy with python 2.7 and PIL 1.1.7:

```
infrapix_single -i river.jpg --show_histogram -o ndvi_river.jpg
Rendering infrablue input image 'river.jpg' to NDVI output image 'ndvi_river.jpg'
river.jpg ndvi_river.jpg
Converting to NDVI...
Traceback (most recent call last):
  File "/usr/local/bin/infrapix_single", line 9, in <module>
    load_entry_point('infrapix==dev', 'console_scripts', 'infrapix_single')()
  File "/usr/local/lib/python2.7/dist-packages/infrapix-dev-py2.7.egg/infrapix/comma   nds/single.py",     line 139, in main
    app.render()
  File "/usr/local/lib/python2.7/dist-packages/infrapix-dev-py2.7.egg/infrapix/comma   nds/single.py",     line 43, in render
    self.render_single(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/infrapix-dev-py2.7.egg/infrapix/comma   nds/single.py",     line 53, in render_single
    ndvi(self.input_file,self.output_file,**self.ndvi_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/infrapix-dev-py2.7.egg/infrapix/proce   ss_infrablue.py",     line 70, in ndvi
    imgR, imgB, imgG = img.split() #get channels
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1497, in split
    if self.im.bands == 1:
AttributeError: 'NoneType' object has no attribute 'bands'
```

**Comment by typpo** [comment]
This is a bug in PIL 1.1.7.  Downgrade to 1.1.6 if possible or apply a patch to Image.py and call `self.load()` before it tries to access bands.

https://mail.python.org/pipermail/image-sig/2010-April/006230.html
